chore(pkg): raise min Node version to `8.*`
As required by transitive dependency `ember-cli-version-checker@4.1.1`.

```

Run yarn install --frozen-lockfile
yarn install v1.22.17
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
warning ember-cli@2.14.2: Invalid bin entry for "🐹" (in "ember-cli").
error ember-cli-version-checker@4.1.1: The engine "node" is incompatible with this module. Expected version "8.* || 10.* || >= 12.*". Got "6.17.1"
error Found incompatible module.
info Visit yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Process completed with exit code 1.
```

https://github.com/ember-intl/cp-validations/runs/4877308058?check_suite_focus=true#step:4:11