chore(pkg): raise min Node version to `10.*`
As required by transitive dependency `resolve-package-path`.

```
Run yarn install --frozen-lockfile
yarn install v1.22.17
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
warning ember-cli@2.14.2: Invalid bin entry for "🐹" (in "ember-cli").
error resolve-package-path@3.1.0: The engine "node" is incompatible with this module. Expected version "10.* || >= 12". Got "8.17.0"
error Found incompatible module.
info Visit yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Process completed with exit code 1.
```

https://github.com/ember-intl/cp-validations/runs/4877330565?check_suite_focus=true#step:4:11